name: Latest Blog Posts Workflow

on:
  schedule:
    # Se ejecuta todos los días a medianoche
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Pull RSS Feed
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          # Reemplaza esta URL con tu feed RSS (ej. Medium, Dev.to, Hashnode, WordPress, etc.)
          feed_list: "https://dev.to/feed/,https://medium.com/feed/@Xanaks15"
          max_post_count: 5
          commit_message: "chore: update latest blog posts in README"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
